{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saicone.rtag",
    "module": "rtag-entity",
    "version": "1.5.11-tj",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rtag-entity-1.5.11-tj.jar",
          "url": "rtag-entity-1.5.11-tj.jar",
          "size": 8150,
          "sha512": "3bfa5fbe234c98f10b3171849b979321476318df7b8424ad7933c8247928567a41f8d66c4d1d36209adf1119869b7b69b95a8a112bfee8f71ddbd79a0c65a299",
          "sha256": "cc2ff915926a0fda9d5d5a748e0caf7e82fd91e23b3d0e1e2cc6bce48c8bb95e",
          "sha1": "c10d9d2dab34e4e8c32ea862e6cc894558d05340",
          "md5": "115ea379f529a42860a317be69d3c48f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.saicone.rtag",
          "module": "rtag",
          "version": {
            "requires": "1.5.11-tj"
          }
        }
      ],
      "files": [
        {
          "name": "rtag-entity-1.5.11-tj.jar",
          "url": "rtag-entity-1.5.11-tj.jar",
          "size": 8150,
          "sha512": "3bfa5fbe234c98f10b3171849b979321476318df7b8424ad7933c8247928567a41f8d66c4d1d36209adf1119869b7b69b95a8a112bfee8f71ddbd79a0c65a299",
          "sha256": "cc2ff915926a0fda9d5d5a748e0caf7e82fd91e23b3d0e1e2cc6bce48c8bb95e",
          "sha1": "c10d9d2dab34e4e8c32ea862e6cc894558d05340",
          "md5": "115ea379f529a42860a317be69d3c48f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rtag-entity-1.5.11-tj-sources.jar",
          "url": "rtag-entity-1.5.11-tj-sources.jar",
          "size": 5388,
          "sha512": "39d1b4400672dd0b57c8edf9f342bc62c1bb627d6e6d9be5563b34167561f6d36675377b99a3f8b3515cfd2222271feb60d04d6b78d57f5fcbad5326ac4ac288",
          "sha256": "4344640a3cd48d7e563ece8a931befa3409117bb119105bcf02a2cda38a783e8",
          "sha1": "ec2de2df9e3621480744dafe63c759c31cd3be68",
          "md5": "28a489cb41d99f2a4ea8e20feba985d4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rtag-entity-1.5.11-tj-javadoc.jar",
          "url": "rtag-entity-1.5.11-tj-javadoc.jar",
          "size": 92171,
          "sha512": "1f9e5027a9db62e3a551dd32a5b93f8e5822faecc7134dddac763a7eb9a6e030ac6a1ed80e06d7df64932534d2538c4d9d5988c9c877afa3d8181806eb088c72",
          "sha256": "0c309c0685fc54b39d8bc69b1e4231287624e6bb221f761e2cd45556fcde39f7",
          "sha1": "8fec1f741494437f3a709e661121777ae7f636a6",
          "md5": "7de9e4c8810a4c9d467fd6bf25eea50c"
        }
      ]
    }
  ]
}
