{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saicone.rtag",
    "module": "rtag-entity",
    "version": "1.5.11-tj",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rtag-entity-1.5.11-tj.jar",
          "url": "rtag-entity-1.5.11-tj.jar",
          "size": 8150,
          "sha512": "adafafef2c397b2b202a2725b76ba60fb1be766a0506f7b54786eda256e2f2146f4035a1e4d2df598054ba242f9376f516e25c5bcc12a2879dfaab87d69313cf",
          "sha256": "1562d6a4914cc302a5ad29ea255a3fb0abbb0377cd1469badb6cdb39e9b4d492",
          "sha1": "aa4a69d069a623e598265691897d5fec4ce1c64e",
          "md5": "fdcb8afe2b40cc1049fc2e8a95f1e18e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.saicone.rtag",
          "module": "rtag",
          "version": {
            "requires": "1.5.11-tj"
          }
        }
      ],
      "files": [
        {
          "name": "rtag-entity-1.5.11-tj.jar",
          "url": "rtag-entity-1.5.11-tj.jar",
          "size": 8150,
          "sha512": "adafafef2c397b2b202a2725b76ba60fb1be766a0506f7b54786eda256e2f2146f4035a1e4d2df598054ba242f9376f516e25c5bcc12a2879dfaab87d69313cf",
          "sha256": "1562d6a4914cc302a5ad29ea255a3fb0abbb0377cd1469badb6cdb39e9b4d492",
          "sha1": "aa4a69d069a623e598265691897d5fec4ce1c64e",
          "md5": "fdcb8afe2b40cc1049fc2e8a95f1e18e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rtag-entity-1.5.11-tj-sources.jar",
          "url": "rtag-entity-1.5.11-tj-sources.jar",
          "size": 5388,
          "sha512": "351d5800818d60218daa6067aab2bf7c083c60933ce4bf54620b8841e11e93e1fa8d5624918bbceb1bace4a8ef457c1a7e30ea7eca656dd100acee149716f1b1",
          "sha256": "3e274db751da8bfab5d66dd418143ccc6006c0c7226a18adcfa855a7399d86a6",
          "sha1": "7bee64b3a45a4084a2a62be7a908b59abc5c535b",
          "md5": "526f5da1d46ab0e64ae3f0254fadae36"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rtag-entity-1.5.11-tj-javadoc.jar",
          "url": "rtag-entity-1.5.11-tj-javadoc.jar",
          "size": 97449,
          "sha512": "9b06a62ee9885cddc4353698bb06010b06b59a1fe485b372f76b13f17050a9181070d9d1067c0105fe43ea20af023f3f4de945091d40ae44147241c638039013",
          "sha256": "5532142ee5ba1c57a601e4dc1cc8d464927bbea4d96c07fb15bd873024db234b",
          "sha1": "0aa13bd212596081b58c15734eab9f0642c1bd46",
          "md5": "0896d828c57948eef2f639f528569059"
        }
      ]
    }
  ]
}
