{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saicone.rtag",
    "module": "rtag-block",
    "version": "1.5.11-tj",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rtag-block-1.5.11-tj.jar",
          "url": "rtag-block-1.5.11-tj.jar",
          "size": 6491,
          "sha512": "0c0e9275b406db968f7fd51d977dfc7067e56e3208ef7c357da47f37b51a3f749b1e96a329a7cfc4a8df114eabc9a8eb6537b4ff91f5d18ae3fd8769fb309c21",
          "sha256": "44b1ed02402d4f8f6685f5e0fc3a174c4fc2db854ecc5b64c61c8d653eabe872",
          "sha1": "da7451cae1ff0e9bee1e4625ac12bbd1f461e4b8",
          "md5": "82d3de280316b5a2c0595597ebb3b2bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.saicone.rtag",
          "module": "rtag",
          "version": {
            "requires": "1.5.11-tj"
          }
        }
      ],
      "files": [
        {
          "name": "rtag-block-1.5.11-tj.jar",
          "url": "rtag-block-1.5.11-tj.jar",
          "size": 6491,
          "sha512": "0c0e9275b406db968f7fd51d977dfc7067e56e3208ef7c357da47f37b51a3f749b1e96a329a7cfc4a8df114eabc9a8eb6537b4ff91f5d18ae3fd8769fb309c21",
          "sha256": "44b1ed02402d4f8f6685f5e0fc3a174c4fc2db854ecc5b64c61c8d653eabe872",
          "sha1": "da7451cae1ff0e9bee1e4625ac12bbd1f461e4b8",
          "md5": "82d3de280316b5a2c0595597ebb3b2bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rtag-block-1.5.11-tj-sources.jar",
          "url": "rtag-block-1.5.11-tj-sources.jar",
          "size": 4340,
          "sha512": "ae8f6738dab702d8af74a5f350cab14ad85337bf5587476f4b105cb6568f674726780041bc098ff1a3f6c1d570b2f535ffbd7cdf558c013cbb4dd36c9c816c33",
          "sha256": "0ac7e0fba25c9b0d9626a0fa154bf855122349ce67170c2f87d2d6e196f3d560",
          "sha1": "d391f51839e1a513f6534341537b358806a3d37a",
          "md5": "46f585b03edcf78a4670f09a32d45406"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rtag-block-1.5.11-tj-javadoc.jar",
          "url": "rtag-block-1.5.11-tj-javadoc.jar",
          "size": 90378,
          "sha512": "c668acb8672ae3ad0860aeeac99dc16df05cc3b7749d0acdfd6c9d2f141917e56b1bbd10960051d3923b6957735bd53169f4153867efd9fb0abf7b4029c7ff18",
          "sha256": "56af367a307935d2246fa4e53ca261819b56520901fdd7ee84b694c441fd2b68",
          "sha1": "91cb6cc7add10d6228883a04ec1acdb859e150ea",
          "md5": "d5e12c4c8426007524f92a1f4088bb13"
        }
      ]
    }
  ]
}
