{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saicone.rtag",
    "module": "rtag-block",
    "version": "1.5.11-tj",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rtag-block-1.5.11-tj.jar",
          "url": "rtag-block-1.5.11-tj.jar",
          "size": 6491,
          "sha512": "cd5b538870907293d7526394d6b9926468b12c2ddccaa0efdfb656a079b71465bebc0934976fc99f73e0435b89b59052975f0684ef773be279bd6858c386b60d",
          "sha256": "d8849ed1a5c345e12dfd26c07608764d0709304eb2d1f689e3246b5d7f0e6f93",
          "sha1": "6c14eb13c130fb943823a4953c967ad6e32ec031",
          "md5": "a908d307f0b95b05f84ca09da75a6c5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.saicone.rtag",
          "module": "rtag",
          "version": {
            "requires": "1.5.11-tj"
          }
        }
      ],
      "files": [
        {
          "name": "rtag-block-1.5.11-tj.jar",
          "url": "rtag-block-1.5.11-tj.jar",
          "size": 6491,
          "sha512": "cd5b538870907293d7526394d6b9926468b12c2ddccaa0efdfb656a079b71465bebc0934976fc99f73e0435b89b59052975f0684ef773be279bd6858c386b60d",
          "sha256": "d8849ed1a5c345e12dfd26c07608764d0709304eb2d1f689e3246b5d7f0e6f93",
          "sha1": "6c14eb13c130fb943823a4953c967ad6e32ec031",
          "md5": "a908d307f0b95b05f84ca09da75a6c5c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rtag-block-1.5.11-tj-sources.jar",
          "url": "rtag-block-1.5.11-tj-sources.jar",
          "size": 4340,
          "sha512": "f5837d98dac7d119102689a9549e8baf9159a664caa1e4dbfc926cc116d9b662daeb3d8137b039ad6bc50568d49e7e067e64c64f4b9ecf0b87e224e3b36b5255",
          "sha256": "eb9ddc5523a8a5b8a492f1d869492a2572a05d267b150d9836c308831827ed5c",
          "sha1": "53fcc599cbe9a538bb6f16bf4df1fb390fc9bde1",
          "md5": "8386ca726b82e91c84225e8495e66484"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rtag-block-1.5.11-tj-javadoc.jar",
          "url": "rtag-block-1.5.11-tj-javadoc.jar",
          "size": 95569,
          "sha512": "2f7a117735cab69922d9a5d03a0dca65e55157d3756616d18e1c6604597774087a9fc97bcf477f4cc5b919b14f1d3d23a36bb669b9117c0a89720e7ced0142f5",
          "sha256": "8d52ad68f18f4409383517c3a5e2d4c0eae8964d3644f4bfd65ef716cca73965",
          "sha1": "805d8ba9488fd822a1f0d7cc99e960343c4b70df",
          "md5": "debe297d23dcf405227d7f9c3dc85663"
        }
      ]
    }
  ]
}
