{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saicone.rtag",
    "module": "rtag",
    "version": "1.5.11-tj",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rtag-1.5.11-tj.jar",
          "url": "rtag-1.5.11-tj.jar",
          "size": 101223,
          "sha512": "3476576c853a047d15f291833a85dd51a4dec1bf1fb0bd01a26896c59c59e8ced660edba2a20c2e288dd43213713e3861a172ddb1d9fef979d50f4cb6bbdea1d",
          "sha256": "59d2380e4c94783b786ffdec38d628df665f6025e84c11d60e34f4bcb026f98a",
          "sha1": "97410b1ca20699870c33839e94dd8110a0ca2668",
          "md5": "7413b6a3db68e30bfb5c8395ce3c4456"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rtag-1.5.11-tj.jar",
          "url": "rtag-1.5.11-tj.jar",
          "size": 101223,
          "sha512": "3476576c853a047d15f291833a85dd51a4dec1bf1fb0bd01a26896c59c59e8ced660edba2a20c2e288dd43213713e3861a172ddb1d9fef979d50f4cb6bbdea1d",
          "sha256": "59d2380e4c94783b786ffdec38d628df665f6025e84c11d60e34f4bcb026f98a",
          "sha1": "97410b1ca20699870c33839e94dd8110a0ca2668",
          "md5": "7413b6a3db68e30bfb5c8395ce3c4456"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rtag-1.5.11-tj-sources.jar",
          "url": "rtag-1.5.11-tj-sources.jar",
          "size": 57415,
          "sha512": "bd7584963e55969d138a38aa43ebab2b2ed261859a7e84da420a6e03e703d1a2321a083ded6bc9aa0c3caf148b1cd2b64e4ed95b393b429bbaa34841ff29b679",
          "sha256": "eedf0fc8199b15b9849984bc3259403ca16955dd98633abc3475b975e5e419cb",
          "sha1": "f4f418f17a8669e9818bcd1a2612edd45237bd1e",
          "md5": "d9675cd07712a887eec1760503b5315d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rtag-1.5.11-tj-javadoc.jar",
          "url": "rtag-1.5.11-tj-javadoc.jar",
          "size": 242520,
          "sha512": "2dbb76c3e101d3f69b58aed1d16f53506a69d33aab1e26730f1a748a792fc416c6af7f5b8937ef51584090312b8b4292d22371380efb0dddce5930effd7595ec",
          "sha256": "e13dc0057525cdf276c5a8c8b8a130240f7b542a3e039cc4f17b11e0fd0e7189",
          "sha1": "1ea737ce9ec6ee3a8ca43761f1d0d57c27c6d452",
          "md5": "d7d7c09090d9c12c9fbcdec9261712d4"
        }
      ]
    }
  ]
}
