{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saicone.rtag",
    "module": "rtag",
    "version": "1.5.11-tj",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rtag-1.5.11-tj.jar",
          "url": "rtag-1.5.11-tj.jar",
          "size": 101230,
          "sha512": "c02ad0431cf1de8c8977ddf72ec44b44fc3de0d488d72d8ac1836d001091bb72f92f7b07af53a255809f65ab38527900a62c657bacc872f84d2a9ea77956c817",
          "sha256": "1c0377b6cebd40dd0c4cb80fa6c5e060a74cfa095fd51dc336283498c9c1cab2",
          "sha1": "5ba7ecdd639a938b1a98250cc37ef5af104674b1",
          "md5": "ba8b7f5202661eb6e41efa266114927d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rtag-1.5.11-tj.jar",
          "url": "rtag-1.5.11-tj.jar",
          "size": 101230,
          "sha512": "c02ad0431cf1de8c8977ddf72ec44b44fc3de0d488d72d8ac1836d001091bb72f92f7b07af53a255809f65ab38527900a62c657bacc872f84d2a9ea77956c817",
          "sha256": "1c0377b6cebd40dd0c4cb80fa6c5e060a74cfa095fd51dc336283498c9c1cab2",
          "sha1": "5ba7ecdd639a938b1a98250cc37ef5af104674b1",
          "md5": "ba8b7f5202661eb6e41efa266114927d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rtag-1.5.11-tj-sources.jar",
          "url": "rtag-1.5.11-tj-sources.jar",
          "size": 57415,
          "sha512": "4a17f9d92618f9f327e811794d2fbf455b6d417e683c6e719f9af7039e733d1a0a474a1f88b9370bbcdf1322fd9cbab234017723970fa23973394dc5d20d5e8d",
          "sha256": "7aa7259181189b95adbd2631025dc194a4cceca8f73f4d44e4ca19d4d0bdae5d",
          "sha1": "5d6a2d0115009a8ecdb308103484c72b88a432ea",
          "md5": "6b371edc3ce39f1fbf77c186cf462085"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rtag-1.5.11-tj-javadoc.jar",
          "url": "rtag-1.5.11-tj-javadoc.jar",
          "size": 247384,
          "sha512": "1c4db6f44891b111f3e802160746335ad4ac4abca8253cba529e6ec413b243503bebb9289e176ca215d3c797558b902c012d864d126b5d6b45e4542aec5ab1e6",
          "sha256": "74139bf6a8ea801677e9eed995e77ea112d519992077477017a146f5e74babba",
          "sha1": "b82691417f4cfd10073d6aec10514f3eb368ccde",
          "md5": "3567a93ddcc078de249e5cac2c7ca025"
        }
      ]
    }
  ]
}
