{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saicone.rtag",
    "module": "rtag-item",
    "version": "1.5.11-tj",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rtag-item-1.5.11-tj.jar",
          "url": "rtag-item-1.5.11-tj.jar",
          "size": 206311,
          "sha512": "3d69123cfa7634eff493918b23bd5ee8354f4e38a1843e7fbad678e85e43026ca18e1a56a2c842747164ef32d14d17e60fa5a3ec6c48b32f5fbec793c3a562b6",
          "sha256": "1a6d03a923430cbabdfd833dbee1c71e3fb17000f788fed6053d1b94f6c01b0c",
          "sha1": "8236a07e46b86b397073aaaa5f27b54d2f49f359",
          "md5": "dc45c15881dab0d343e4ba0d27716a75"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.saicone.rtag",
          "module": "rtag",
          "version": {
            "requires": "1.5.11-tj"
          }
        }
      ],
      "files": [
        {
          "name": "rtag-item-1.5.11-tj.jar",
          "url": "rtag-item-1.5.11-tj.jar",
          "size": 206311,
          "sha512": "3d69123cfa7634eff493918b23bd5ee8354f4e38a1843e7fbad678e85e43026ca18e1a56a2c842747164ef32d14d17e60fa5a3ec6c48b32f5fbec793c3a562b6",
          "sha256": "1a6d03a923430cbabdfd833dbee1c71e3fb17000f788fed6053d1b94f6c01b0c",
          "sha1": "8236a07e46b86b397073aaaa5f27b54d2f49f359",
          "md5": "dc45c15881dab0d343e4ba0d27716a75"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rtag-item-1.5.11-tj-sources.jar",
          "url": "rtag-item-1.5.11-tj-sources.jar",
          "size": 71771,
          "sha512": "5b4c9a521c9dd469880534139129d637c526b689b030d9a912974f556c99cadb7c8f80f6538be14389635d7db01bf3f77a3ed84082330ab9764487ef218a29e3",
          "sha256": "961a2f5fab769ab415f1429fb60f621675353f3a1d82c73234c1228e99a3e90a",
          "sha1": "8cab05d8adb7a616b151dbdd70dbd2d9ac61cb1e",
          "md5": "119a78e72bf3fb7d7c644bf5697f29fa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rtag-item-1.5.11-tj-javadoc.jar",
          "url": "rtag-item-1.5.11-tj-javadoc.jar",
          "size": 379685,
          "sha512": "397d1d92b0920aaff8bbb254c371156ff9ce38286cb87ad9d8f3d3123399b3d13684d1dabb5d3e737cff5b28191c2ac4dc0bd520274af7267562aa56ad6adc6d",
          "sha256": "9370c43edc96a82def69c11809d319d9abf40a1de96df8fef9246fe9c6e6625c",
          "sha1": "945181721989c9611d4d00cb43b568245ab6c8b5",
          "md5": "6cf1c482134629d2eb6d460399f01ec7"
        }
      ]
    }
  ]
}
