{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saicone.rtag",
    "module": "rtag-item",
    "version": "1.5.11-tj",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rtag-item-1.5.11-tj.jar",
          "url": "rtag-item-1.5.11-tj.jar",
          "size": 206301,
          "sha512": "ea1d6bea192433f435d2dd5a3269c7482a5301675c8fb14c842e1b3118cc70349ba65a14a6009819994df902e6b76eff223e95b377c7d8f28620c0d14e250c38",
          "sha256": "21b027d7037a7bebb1923a596e337317db5ed91b7d16696befb77c04d26aca63",
          "sha1": "d6ca3bc5634845d68e62c2c7e09a3ba29e589c7e",
          "md5": "aa2f13233cbf8e72f84ea1c1729f2981"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.saicone.rtag",
          "module": "rtag",
          "version": {
            "requires": "1.5.11-tj"
          }
        }
      ],
      "files": [
        {
          "name": "rtag-item-1.5.11-tj.jar",
          "url": "rtag-item-1.5.11-tj.jar",
          "size": 206301,
          "sha512": "ea1d6bea192433f435d2dd5a3269c7482a5301675c8fb14c842e1b3118cc70349ba65a14a6009819994df902e6b76eff223e95b377c7d8f28620c0d14e250c38",
          "sha256": "21b027d7037a7bebb1923a596e337317db5ed91b7d16696befb77c04d26aca63",
          "sha1": "d6ca3bc5634845d68e62c2c7e09a3ba29e589c7e",
          "md5": "aa2f13233cbf8e72f84ea1c1729f2981"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rtag-item-1.5.11-tj-sources.jar",
          "url": "rtag-item-1.5.11-tj-sources.jar",
          "size": 71763,
          "sha512": "969aa52307df811ae1a6868599496708b5c76c8b45c1e260be03d36291b78b6f92e625f9929e92a0aa8732d0ecfbb12b12b67ba8607b5b5d51aa6730eac91353",
          "sha256": "7f1ece182ea3237eb5fc10298ac8265d3be13ea844271f8505d9992ca52acdc5",
          "sha1": "0c8ba22cf2e06fcffbfd3e090dd10973de4dd5c6",
          "md5": "45a10078a9d55bcccf1d152809aae6b7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rtag-item-1.5.11-tj-javadoc.jar",
          "url": "rtag-item-1.5.11-tj-javadoc.jar",
          "size": 372537,
          "sha512": "f68fca97ef3576eed59c7b9cf598d05e6007dffc144911d4a51cc55e6eac222b742b1d0968293cc5017e02bb8c5dd0a7f781962c267b891ed7b278f06246e281",
          "sha256": "7eee5f58337dde3ce3e9ccb8b781a7e75e781de6309ebfac7e996539afe2656a",
          "sha1": "3f202c309a5b46124522656dde28cc094e2cd21e",
          "md5": "0740b9c890ee8a9587ddebfe6d827991"
        }
      ]
    }
  ]
}
